[project]
name = "comfyui_custom_nodes_gayrat"
description = "Nodes:GoogleTranslate, ImageResize"
version = "1.0.1"
license = { file = "LICENSE" }

[project.urls]
Repository = "https://github.com/gayratv/ComfyUI_Gayrat"

[tool.comfy]
PublisherId = "gayrat"
DisplayName = "ComfyUI_Gayrat"
Icon = ""
